<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $callForPrice = $_product->getCallForPriceActive(); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
			<?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
			<?php endif; ?>
            <div class="actions">
				<?php if ($_product->isSaleable() && !$this->helper('FZ\CallForPrice\Helper\Data')->isEnable($_product->getData('call_for_price_active'))) : ?>
                    <!-- Cart button start -->
                    <button type="submit"
                            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                            class="action primary tocart"
                            id="product-addtocart-button" disabled>
                        <span><?= $block->escapeHtml($buttonTitle) ?></span>
                    </button>
                    <!-- Cart button stop -->
				<?php else: ?>
					<?php $buttontext = $this->helper('FZ\CallForPrice\Helper\Data')->getButtonText(); ?>
                    <a href="javascript:void(0)" id="call-for-price" target="_self"
                       class="action primary tocart callfor-price"><span><?php echo $buttontext; ?></span></a>
				<?php endif; ?>
				<?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

</script>
